export const sample_foods = [
  {
    id: "1",
    name: "Hot Coffee",
    price: 4.50,
    imageUrl: "hot coffee.jpg",
    tags: ['Drinks'],
  },
  {
    id: "2",
    name: "Iced Coffee",
    price: 4.50,
    imageUrl: "icedcoffee.jpg",
    tags: ['Drinks'],
  },
  {
    id: "3",
    name: "Americano ",
    price: 5.00,
    imageUrl: "americano.jpg",
    tags: ['Drinks'],
  },
  {
    id: "4",
    name: "Latte",
    price: 5.50,
    imageUrl: "latte.jpg",
    tags: ['Drinks'],
  },
  {
    id: "5",
    name: "Iced Latte",
    price: 5.50,
    imageUrl: "icedlatte.jpg",
    tags: ['Drinks'],
  },
  {
    id: "6",
    name: "Macchiato",
    price: 6.00,
    imageUrl: "macchiato.jpg",
    tags: ['Drinks'],
  },
  {
    id: "7",
    name: "Frappe",
    price: 6.00,
    imageUrl: "frappe.jpg",
    tags: ['Drinks'],
  },
  {
    id: "8",
    name: "Cappuccino",
    price: 6.25,
    imageUrl: "cappuccino.jpg",
    tags: ['Drinks'],
  },
  {
    id: "9",
    name: "Mocha",
    price: 6.25,
    imageUrl: "mocha.jpg",
    tags: ['Drinks'],
  },
  {
    id: "10",
    name: "Flat White",
    price: 6.00,
    imageUrl: "flat white.jpg",
    tags: ['Drinks'],
  },
  {
    id: "11",
    name: "Cold Brew",
    price: 6.50,
    imageUrl: "cold brew.jpg",
    tags: ['Drinks'],
  },
  {
    id: "12",
    name: "Chai Latte",
    price: 5.75,
    imageUrl: "chai latte.jpg",
    tags: ['Drinks'],
  },
  {
    id: "13",
    name: "Chocolate Chip Cookie",
    price: 1.25,
    imageUrl: "chocolate chip cookie.jpg",
    tags: ['Bakery'],
  },
  {
    id: "14",
    name: "Sugar Cookie",
    price: 1.25,
    imageUrl: "sugar cookie.jpg",
    tags: ['Bakery'],
  },
  {
    id: "15",
    name: "Cheese Danish",
    price: 3.25,
    imageUrl: "cheese danish.jpg",
    tags: ['Bakery'],
  },
  {
    id: "16",
    name: "Blueberry Muffin",
    price: 3.25,
    imageUrl: "blueberry muffin.jpg",
    tags: ['Bakery'],
  },
  {
    id: "17",
    name: "Chocolate Muffin",
    price: 3.25,
    imageUrl: "chocolate muffin.jpg",
    tags: ['Bakery'],
  },
  {
    id: "18",
    name: "Banana Bread",
    price: 2.50,
    imageUrl: "banana bread.jpg",
    tags: ['Bakery'],
  },
  {
    id: "19",
    name: "Ham & Cheese Wrap",
    price: 7.00,
    imageUrl: "ham and cheese wrap.jpg",
    tags: ["Wraps"],
  },
  {
    id: "20",
    name: "Breakfast Wrap",
    price: 8.00,
    imageUrl: "breakfast wrap.jpg",
    tags: ["Wraps"],
  },
  {
    id: "21",
    name: "BLT Wrap",
    price: 8.75,
    imageUrl: "blt wrap.jpeg",
    tags: ["Wraps"],
  },
];

export const sample_tags = [
  { name: "All", count: 21 },
  { name: "Drinks", count: 12 },
  { name: "Bakery", count: 6 },
  { name: "Wraps", count: 3 },
];
