export const sample_foods = [
  {
    id: "1",
    name: "Hot Coffee",
    price: 4.50,
    imageUrl: "hot coffee.jpg",
    shortdesc: "Caffeinated/Decaffeinated",
    description: "Black coffee made from freshly brewed coffee beans mixed with hot water. Served either caffeinated or decaffeinated.",
    tags: ["Drinks"],
  },
  {
    id: "2",
    name: "Iced Coffee",
    price: 4.50,
    imageUrl: "icedcoffee.jpg",
    shortdesc: "",
    description: "Coffee crafted with care from premium beans and served over ice. Customizable with milk or syrups.",
    tags: ["Drinks"],
  },
  {
    id: "3",
    name: "Americano ",
    price: 5.00,
    imageUrl: "americano.jpg",
    shortdesc: "Iced/Hot, Vanilla/Caramel/Hazelnut",
    description: "Made by adding hot water to a shot of espresso, our Americano retains the boldness of espresso while offering a lighter flavor profile.",
    tags: ["Drinks"],
  },
  {
    id: "4",
    name: "Latte",
    price: 5.50,
    imageUrl: "latte.jpg",
    shortdesc: "Vanilla/Hazelnut/Matcha",
    description: "The perfect blend of espresso and steamed milk. Topped with light foam, this drink offers a blend of rich espresso flavor and creamy texture. Served hot.",
    tags: ["Drinks"],
  },
  {
    id: "5",
    name: "Iced Latte",
    price: 5.50,
    imageUrl: "icedlatte.jpg",
    shortdesc: "Vanilla/Hazelnut/Matcha",
    description: "A smooth and creamy drink made by blending rich espresso with cold milk over ice. ",
    tags: ["Drinks"],
  },
  {
    id: "6",
    name: "Macchiato",
    price: 6.00,
    imageUrl: "macchiato.jpg",
    shortdesc: "Vanilla/Caramel",
    description: "A blend of bold espresso and velvety milk foam with caramel drizzled on top.",
    tags: ["Drinks"],
  },
  {
    id: "7",
    name: "Frappé",
    price: 6.00,
    imageUrl: "frappe.jpg",
    shortdesc: "Caramel/Chocolate/Vanilla Bean",
    description: "Blended to perfection, our frappé combines chilled coffee, ice, and cream for a refreshing, sweet treat.",
    tags: ["Drinks"],
  },
  {
    id: "8",
    name: "Cappuccino",
    price: 6.25,
    imageUrl: "cappuccino.jpg",
    shortdesc: "",
    description: "A shot of espresso topped with equal parts steamed milk and velvety foam.",
    tags: ["Drinks"],
  },
  {
    id: "9",
    name: "Mocha",
    price: 6.25,
    imageUrl: "mocha.jpg",
    shortdesc: "",
    description: "A combination of rich espresso, decadent chocolate, and creamy steamed milk. Topped with whipped cream, chocolate shavings, and cocoa powder.",
    tags: ["Drinks"],
  },
  {
    id: "10",
    name: "Flat White",
    price: 6.00,
    imageUrl: "flat white.jpg",
    shortdesc: "",
    description: "Contains a double shot of espresso topped with creamy, velvety steamed milk.",
    tags: ["Drinks"],
  },
  {
    id: "11",
    name: "Cold Brew",
    price: 6.50,
    imageUrl: "cold brew.jpg",
    shortdesc: "",
    description: "Made by steeping coarse coffee grounds in cold water for an extended period. Served over ice with fresh milk poured on top.",
    tags: ["Drinks"],
  },
  {
    id: "12",
    name: "Chai Latte",
    price: 5.75,
    imageUrl: "chai latte.jpg",
    shortdesc: "Dirty/Vanilla/Pumpkin Spice",
    description: "Made by infusing aromatic chai with steamed milk and a touch sweetness. Served hot.",
    tags: ["Drinks"],
  },
  {
    id: "13",
    name: "Chocolate Chip Cookie",
    price: 1.25,
    imageUrl: "chocolate chip cookie.jpg",
    shortdesc: "coff",
    description: "Our classic chocolate chip cookie, baked with a golden brown crust and loaded with chocolate chips.",
    tags: ["Bakery"],
  },
  {
    id: "14",
    name: "Sugar Cookie",
    price: 1.25,
    imageUrl: "sugar cookie.jpg",
    shortdesc: "coff",
    description: "Freshly baked to golden perfection and delicately sweetened.",
    tags: ["Bakery"],
  },
  {
    id: "15",
    name: "Cheese Danish",
    price: 3.25,
    imageUrl: "cheese danish.jpg",
    shortdesc: "",
    description: "Our flaky cheese danish, filled with a creamy blend of sweet cheese and wrapped in buttery pastry.",
    tags: ["Bakery"],
  },
  {
    id: "16",
    name: "Blueberry Muffin",
    price: 3.25,
    imageUrl: "blueberry muffin.jpg",
    shortdesc: "",
    description: "Our freshly baked blueberry muffin, baked to perfection with plump blueberries and topped with a delicate crumb.",
    tags: ["Bakery"],
  },
  {
    id: "17",
    name: "Chocolate Muffin",
    price: 3.25,
    imageUrl: "chocolate muffin.jpg",
    shortdesc: "cff",
    description: "Our freshly baked chocolate muffin, crafted with rich cocoa and filled with chocolate chips.",
    tags: ["Bakery"],
  },
  {
    id: "18",
    name: "Banana Bread",
    price: 2.50,
    imageUrl: "banana bread.jpg",
    shortdesc: "",
    description: "Our homemade banana bread, baked with ripe bananas and a hint of cinnamon for a moist and flavorful treat.",
    tags: ["Bakery"],
  },
  {
    id: "19",
    name: "Ham & Cheese Wrap",
    price: 7.00,
    imageUrl: "ham and cheese wrap.jpg",
    shortdesc: "",
    description: "Made with premium ham, melted white cheddar cheese, spinach, bacon, and wrapped in a soft tortilla.",
    tags: ["Wraps"],
  },
  {
    id: "20",
    name: "Breakfast Wrap",
    price: 8.00,
    imageUrl: "breakfast wrap.jpg",
    shortdesc: "",
    description: "Start your day right with our breakfast wrap, filled with scrambled eggs, bacon, and melted cheddar cheese, ",
    tags: ["Wraps"],
  },
  {
    id: "21",
    name: "BLT Wrap",
    price: 8.75,
    imageUrl: "blt wrap.jpeg",
    shortdesc: "",
    description: "Our classic BLT wrap, packed with turkey, crispy bacon, fresh lettuce, tomatoes, and mayonnaise.",
    tags: ["Wraps"],
  },
];

export const sample_tags = [
  { name: "All", count: 21 },
  { name: "Drinks", count: 12 },
  { name: "Bakery", count: 6 },
  { name: "Wraps", count: 3 },
];
